version: "3.9"

name: local-wren

services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - TZ=${TZ}
    volumes:
      - ./volumes/ollama:/root/.ollama
      - ./models:/models:ro
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    gpus: all

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
    environment:
      - TZ=${TZ}
    volumes:
      - ./volumes/qdrant:/qdrant/storage

  api:
    build:
      context: ./services/api
    depends_on:
      - ollama
      - qdrant
    environment:
      - TZ=${TZ}
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - EMBED_MODEL=${EMBED_MODEL}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    ports:
      - "${API_PORT}:8000"

  worker:
    build:
      context: ./services/worker
    depends_on:
      - ollama
      - qdrant
    environment:
      - TZ=${TZ}
      - OLLAMA_URL=http://ollama:11434
      - EMBED_MODEL=${EMBED_MODEL}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
    volumes:
      - ./data:/data:ro

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    depends_on:
      - ollama
    environment:
      - TZ=${TZ}
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "${OPENWEBUI_PORT}:8080"
    volumes:
      - openwebui-data:/app/backend/data
    restart: unless-stopped

volumes:
  openwebui-data:

networks:
  default:
    name: local-wren-net